site_name: Robokassa Docs
site_url: https://rk-sales.github.io/docs/

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: white
      accent: blue

extra_css:
  - extra.css
  
plugins:
  - search
  - section-index
  
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md

  - Приём платежей:
      - Платёжные методы:
          - priem-platezhey/platezhnye-metody/index.md
          - Карты РФ: priem-platezhey/platezhnye-metody/cards-rf.md
          - Иностранные карты: priem-platezhey/platezhnye-metody/cards-foreign.md
          - СБП: priem-platezhey/platezhnye-metody/sbp.md
          - Sber Pay: priem-platezhey/platezhnye-metody/sberpay.md
          - T-Pay: priem-platezhey/platezhnye-metody/tpay.md
          - MTS Pay: priem-platezhey/platezhnye-metody/mts-pay.md
          - Alfa Pay: priem-platezhey/platezhnye-metody/alfa-pay.md
          - Yandex Pay (с двойным кэшбэком): priem-platezhey/platezhnye-metody/yandex-pay.md
          - Mir Pay (с двойным кэшбэком): priem-platezhey/platezhnye-metody/mir-pay.md
          - Оплата частями «Подели»: priem-platezhey/platezhnye-metody/podeli.md
          - Оплата частями «Yandex Split»: priem-platezhey/platezhnye-metody/yandex-split.md
          - Оплата частями «Мокка»: priem-platezhey/platezhnye-metody/mokka.md
          - Рассрочка / кредит ОТП-Банк: priem-platezhey/platezhnye-metody/otp-credit.md
          - Рассрочка через карту «Халва»: priem-platezhey/platezhnye-metody/halva.md
          - ЮMoney кошелёк: priem-platezhey/platezhnye-metody/yoomoney.md
      - Функции Robokassa:
          - priem-platezhey/funktsii/index.md
          - Мультибанкинг: priem-platezhey/funktsii/multibanking.md
          - Формирование ссылок на оплату: priem-platezhey/funktsii/payment-links.md
          - Холдирование платежей: priem-platezhey/funktsii/hold.md
          - Рекуррентные платежи (подписки): priem-platezhey/funktsii/recurring.md
          - Сплитование (деление платежей на разные компании): priem-platezhey/funktsii/split.md
          - Мультиаккаунт: priem-platezhey/funktsii/multiaccount.md
          - Брендирование платёжной формы: priem-platezhey/funktsii/branding.md
      - Чеки и ФЗ-54 (Фискализация платежей):
          - priem-platezhey/fz-54/index.md
          - Робочеки (Бесплатная Онлайн-Касса): priem-platezhey/fz-54/robocheki.md
          - Робокасса-Онлайн (Аренда облачной кассы): priem-platezhey/fz-54/robokassa-online.md
          - Робочеки СМЗ (Чеки для самозанятых и ИП на НПД): priem-platezhey/fz-54/robocheki-smz.md

  - Подключение:
      - Инструкция подключения для ИП: podklyuchenie/ip.md
      - Инструкция подключения для ООО: podklyuchenie/ooo.md
      - Инструкция подключения для СМЗ: podklyuchenie/smz.md
      - Требования к подключаемым веб-ресурсам:
          - Требования к сайтам: podklyuchenie/trebovaniya/sites.md
          - Требования к сообществу VK: podklyuchenie/trebovaniya/vk.md
          - Требования к Telegram‑каналу или боту: podklyuchenie/trebovaniya/telegram.md
          - Требования к мобильному приложению: podklyuchenie/trebovaniya/mobile-app.md
          
  - Инструкции и обучение:
      - Работа через ЛК (login.robokassa.ru):
          - Вывод и автовывод денежных средств: instructions/lk-robokassa/vyvod.md
          - Выставление разовой ссылки на оплату: instructions/lk-robokassa/dynamic-link.md
          - Выставление многоразовой ссылки на оплату: instructions/lk-robokassa/static-link.md
          - Выставление ссылок с регулярным списанием (подписка): instructions/lk-robokassa/sub-link.md
          - Как оформить возврат средств покупателю: instructions/lk-robokassa/vozvrat.md
          - Как настроить уведомления об успешных платежах: instructions/lk-robokassa/payment-notify.md
          - Как выдать персональный доступ для сотрудников к ЛК: instructions/lk-robokassa/roles.md
          - Как подключить фискализацию:
              - Аренда Облачной Кассы - Robokassa Online: instructions/lk-robokassa/fz-54/robokassa-online.md
              - Включение сервиса «Робочеки»: instructions/lk-robokassa/fz-54/robocheki.md
              - Подключение внешней интеграции: 
                  - Комтет-касса: instructions/lk-robokassa/fz-54/external-integration/komtet-kassa.md
                  - Эвотор: instructions/lk-robokassa/fz-54/external-integration/evotor.md
                  - Атол-онлайн: instructions/lk-robokassa/fz-54/external-integration/atol-online.md
                  - Первый ОФД: instructions/lk-robokassa/fz-54/external-integration/perviy-ofd.md
                  - Бизнес.Ру Онлайн-Чеки: instructions/lk-robokassa/fz-54/external-integration/biznes-ru.md
                  - LiteBox: instructions/lk-robokassa/fz-54/external-integration/litebox.md
                  - Инит-Про: instructions/lk-robokassa/fz-54/external-integration/init-pro.md
                  - Модуль-Касса: instructions/lk-robokassa/fz-54/external-integration/modul-kassa.md
                  - МТС-Касса: instructions/lk-robokassa/fz-54/external-integration/mts.md
      - Работа через Мобильное Приложение (pwa.robokassa.ru):
          - Выставление разовой ссылки на оплату: instructions/app-robokassa/app-paylink.md
          - Как оформить возврат средств покупателю: instructions/app-robokassa/app-vozvrat.md
          - Как отслеживать поступления платежей: instructions/app-robokassa/app-paynotify.md
          
      - Работа через Telegram бота / VK бота: instructions/tg-vk-links.md
      - Создание Интернет-Магазина на базе Robokassa:
          - Robomarket: instructions/rk-shops/robomarket.md
          - RobokassaShopBot в Telegram: instructions/rk-shops/rkshop-bot.md

  - Готовые интеграции и API: integratsii/index.md

  - Мобильное приложение Robokassa: mobile-app/index.md

